### PR TITLE
Fixed #1 and made it a tiny bit faster too

### PR DESCRIPTION
**Pull request by ademakov**

### CODE REVIEW

**Comment by pascaldekloe** [comment]
On my machine the memory table is slower. I'd favour a subtraction and two bit shifts over a memory lookup and a logical and. What kind of hardware are you running on @ademakov?

**Comment by ademakov** [comment]
Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz

gcc (MacPorts gcc6 6.3.0_2) 6.3.0

**Comment by pascaldekloe** [comment]
Maybe memory access got faster on those new machines? How big is the win on the benchmark? Is it worth accessing the memory bridge (and cache pollution)?

**Comment by ademakov** [comment]
Your version:

./bench.bin
took 3.948104ns for 1000dM

My version:

./bench.bin
took 3.483250ns for 1000dM

**Comment by pascaldekloe** [comment]
Over 10% on the full-cycle looks highly unlikely. Maybe the compiler is playing tricks? I'll have a look into GCC and the resulting assembly this weekend.

**Comment by ademakov** [comment]
Your version: 

On Intel(R) Xeon(R) CPU           E5520  @ 2.27GHz
took 6.299231ns for 1000dM
On Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz
took 4.778892ns for 1000dM

My version:

On Intel(R) Xeon(R) CPU           E5520  @ 2.27GHz
took 5.643248ns for 1000dM
On Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz
took 4.291535ns for 1000dM

gcc (Debian 6.3.0-18) 6.3.0 20170516

**Comment by pascaldekloe** [comment]
Just tried GCC 6.3 and it's still slower on my aging i5-2520M.
```
% make CC=gcc bench
rm -fr test.bin bench.bin
gcc -o bench.bin -O3 bench.c
./bench.bin
took 8.584438ns for 1000dM
% git checkout master
Previous HEAD position was 4f1a058... Merge pull request #3 from ademakov/master
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.
% make CC=gcc bench
rm -fr test.bin bench.bin
gcc -o bench.bin -O3 bench.c
./bench.bin
took 8.320004ns for 1000dM
```

The difference is:
```assembly
        leaq    mask.1798(%rip), %rsi
        leal    1(%rcx), %eax
        movslq  %ecx, %rcx
        andq    (%rsi,%rcx,8), %rdx
```
... versus:
```assembly
        addl    $1, %eax
        movl    $8, %ecx
        subl    %eax, %ecx
        sall    $3, %ecx
        salq    %cl, %rdx
        shrq    %cl, %rdx
```

Going to buy a new Mac Pro now. To be continued...

**Comment by pascaldekloe** [comment]
@ademakov, I stand corrected. The difference is huge on a E5-1650 v2.

**Pull request merged**
